models:
  - name: fct_hotel_bookings
    columns:
      - name: hotel_id
        tests:
          - not_null
      - name: is_canceled
      - name: arrival_date_day_of_month
      - name: country
      - name: reservation_status